name: piano_agent

description: >
  PyTune Piano Agent — guides the user in describing their piano and builds an emotional profile. Starts with a photo if possible.

triggers:
  - event: page_visit
    condition: current_page == "/pianos"

context:
  fetch:
    - user_profile
  extra:
    - raw_user_input
    - first_piano
  variables:
    first_piano: first_piano
    no_piano: not first_piano or not first_piano.brand
    has_basic_info: first_piano.brand and first_piano.model
    is_confirmed: first_piano.confirmed is True
    can_save: first_piano.brand and first_piano.category and (first_piano.size_cm or first_piano.model) and (first_piano.serial_number or first_piano.year_estimated)
    show_serial_help: not first_piano or not first_piano.serial_number

conversation:
  - if: raw_user_input
    say: ${llm_response}
    actions: []

  - elif: no_piano
    say: >
      You can type, speak using the 🎤 icon, upload photos, or fill in the form below to describe your piano.

      For example:  
      • **Blüthner upright**  
      • **Yamaha C3**  
      • **Upright 120cm**  
      • or simply upload photos if unsure.
    actions:
      - trigger_event: set_placeholder
        suggest_action: ""
        params:
          value: "Brand, type (upright/grand), model or size, serial number…"
      - suggest_action: "Guided upload photos"
        trigger_event: open_photo_guide
      - suggest_action: "Where is the serial number?"
        trigger_event: show_serial_help
        if: show_serial_help

  - elif: first_piano.brand and not first_piano.category
    say: >
      Great! What kind of piano is it — upright or grand?
    actions: []

  - elif: has_basic_info and not is_confirmed
    say: >
      I understood your piano is a **{{ first_piano.brand }} {{ first_piano.model }}**.  
      Do you confirm this information?
    actions:
      - suggest_action: "Yes, that’s correct"
        trigger_event: confirm_piano
      - suggest_action: "No, let me update it"
        route_to: "/pianos"

  - elif: first_piano and first_piano.category and first_piano.size_cm and not is_confirmed
    say: >
      Does everything look correct? You can confirm the piano if the information seems accurate.
    actions:
      - suggest_action: "Confirm my piano"
        trigger_event: confirm_piano

  - elif: not first_piano.model and not first_piano.size_cm
    say: >
      Do you happen to know the model name or number?
    actions:
      - suggest_action: "It’s a Grand piano, about 190cm"
        trigger_event: fill_piano_size

  - elif: not first_piano.serial_number
    say: >
      If you have the serial number, I can estimate the year.
    actions:
      - suggest_action: "Add serial number"
        route_to: "/pianos"
      - suggest_action: "Where is the serial number?"
        trigger_event: show_serial_help
        if: show_serial_help

  - elif: not first_piano.year_estimated
    say: >
      If you’re not sure of the year, I can try to estimate it based on brand or serial number.
    actions:
      - suggest_action: "Estimate year"
        route_to: "/pianos/dating"

  - elif: can_save and not is_confirmed
    say: >
      You’ve entered enough information to register your piano. Would you like to save it now?
    actions:
      - suggest_action: "Save my piano"
        trigger_event: save_piano

  - elif: is_confirmed
    say: >
      ✅ Your piano has been successfully saved.  
      Would you like to upload photos of it (optional)?
    actions:
      - suggest_action: "Upload photos"
        trigger_event: trigger_upload
      - suggest_action: "Skip this step"
        trigger_event: skip_upload

  - elif: not user_profile.music_start_age
    say: >
      When did you start playing the piano, just out of curiosity?
    actions: []

  - elif: not user_profile.music_style or not user_profile.skill_level
    say: >
      What kind of music do you enjoy playing? And how would you describe your level?
    actions: []

  - else: true
    continue_if: first_piano.brand and first_piano.category and (first_piano.model or first_piano.size_cm)
    say: >
      Thank you so much for sharing all this with me, {{ firstname }}!  
      You can now explore diagnosis, tutorials, or tuning options below.
    actions:
      - suggest_action: "Start diagnosis"
        route_to: "/diagnosis"
      - suggest_action: "Explore tuning options"
        route_to: "/tuner"

metadata:
  version: "2.9"
  lang: en
  allow_interruptions: true
  llm_backend: openai
  llm_model: gpt-3.5-turbo
  memory: true
