name: piano_agent
description: >
  PyTune Piano Agent — guides the user step-by-step to describe and save their piano. Then opens a musical conversation.

start:
  say: >
    📸 **Upload photos** to identify your piano automatically

    💬 Or type something like: `Blüthner upright`, `Yamaha C3`, `120cm upright`
    
    🎙️ You can also use the microphone to describe it aloud  

  actions:
    - trigger_event: set_placeholder
      suggest_action: ""
      params:
        value: "Brand, type (upright/grand), model or size, serial number…"

    - suggest_action: "Guided upload photos"
      trigger_event: open_photo_guide

    - suggest_action: "Where is the serial number?"
      trigger_event: show_serial_help
    
    - suggest_action: "How to measure size?"
      trigger_event: show_size_help

triggers:
  - event: page_visit
    condition: current_page == "/pianos"

context:
  fetch:
    - user_profile
  extra:
    - raw_user_input
    - first_piano
    - dont_know_flags
    - metadata
  variables:
    first_piano: first_piano
    no_brand: not first_piano or not first_piano.brand
    no_category: first_piano.brand and not first_piano.category
    no_model: first_piano.category and not first_piano.model and not first_piano.model_dont_know
    no_size: (first_piano.model or first_piano.model_dont_know) and (not first_piano.size_cm or first_piano.size_cm == 0)
    no_serial: not first_piano.serial_number and not first_piano.serial_dont_know
    is_confirmed: first_piano.confirmed is True
    can_save: first_piano.brand and first_piano.category and (first_piano.model or first_piano.size_cm > 0)
    identified_from_image: metadata.extracted_from_image is True
    show_serial_help: not first_piano or not first_piano.serial_number
    hide_serial_help: first_piano and first_piano.serial_number

conversation:
  - if: raw_user_input
    say: ${llm_response}
    actions: []

  - elif: no_brand
    say: >
      Let's start with the brand. What brand is your piano?
    actions: []

  - elif: no_category
    say: >
      What type of piano is it — upright or grand?
    actions: []

  - elif: no_model
    say: >
      Do you happen to know the model name or number?
    actions:
      - suggest_action: "I don’t know the model"
        trigger_event: set_model_dont_know

  - elif: no_size
    say: >
      Do you know the piano's size? (For upright: height. For grand: length)
    actions:
      - suggest_action: "I don’t know the size"
        trigger_event: set_size_dont_know

  - elif: no_serial
    say: >
      If you have the serial number, I can estimate the year.
    actions:
      - suggest_action: "Add serial number"
        route_to: "/pianos"
      - suggest_action: "I don’t know the serial number"
        trigger_event: set_serial_dont_know
      - suggest_action: "Where is the serial number?"
        trigger_event: show_serial_help
        if: show_serial_help

  - elif: can_save and not is_confirmed
    say: >
      You've entered enough information to register your piano. Please confirm if correct.
    actions:
      - suggest_action: "Confirm my piano"
        trigger_event: confirm_piano

  - elif: is_confirmed and identified_from_image
    say: >
      ✅ Your piano has been successfully confirmed from photos and saved.
      Would you like to receive your full report by email?
    actions:
      - suggest_action: "📄 Receive full report"
        trigger_event: trigger_pdf_send
      - suggest_action: "Skip this step"
        trigger_event: skip_pdf_send
  
  - elif: first_piano.skip_pdf_sent is true
    continue: true
    say: >
      Alright, no problem — let’s move on.

  - elif: first_piano.report_sent is true
    continue: true
    say: >
      ✅ The report has been sent! Let’s continue.


  - elif: is_confirmed and not identified_from_image and not first_piano.skipped_upload
    say: >
      ✅ Your piano has been successfully saved. Would you like to upload photos of it (optional)? Click ➕
    actions:
      - suggest_action: "Upload photos"
        trigger_event: trigger_upload
      - suggest_action: "Skip this step"
        trigger_event: skip_upload

  - elif: is_confirmed and (identified_from_image or first_piano.skipped_upload)
    continue: true
    say: ${llm_response}
    actions: []

  - elif: not user_profile.music_start_age
    say: >
      When did you start playing the piano, just out of curiosity?
    actions: []

  - elif: not user_profile.music_style or not user_profile.skill_level
    say: >
      What kind of music do you enjoy playing? And how would you describe your level?
    actions: []

  - else: true
    continue_if: first_piano.brand and first_piano.category and (first_piano.model or first_piano.size_cm)
    say: >
      Thank you so much for sharing all this with me, ${firstname}! You can now explore diagnosis, tutorials, or tuning options below.
    actions:
      - suggest_action: "Start diagnosis"
        route_to: "/diagnosis"
      - suggest_action: "Explore tuning options"
        route_to: "/tuner"

metadata:
  version: "3.0"
  title: "🎹 Pytune Piano Agent Assistant"
  lang: en
  allow_interruptions: true
  llm_backend: openai
  llm_model: gpt-4o-mini
  memory: true
  form_context_key: first_piano
