name: piano_agent
description: >
  PyTune Piano Agent — guides the user step-by-step to describe and save their piano. Then opens a musical conversation.

triggers:
  - event: page_visit
    condition: current_page == "/pianos"

context:
  fetch:
    - user_profile
  extra:
    - raw_user_input
    - first_piano
  variables:
    first_piano: first_piano
    no_brand: not first_piano or not first_piano.brand
    no_category: first_piano.brand and not first_piano.category
    no_model: first_piano.category and not first_piano.model and not first_piano.model_dont_know
    no_size: (first_piano.model or first_piano.model_dont_know) and (not first_piano.size_cm or first_piano.size_cm == 0)
    no_serial: not first_piano.serial_number and not first_piano.serial_dont_know
    is_confirmed: first_piano.confirmed is True
    can_save: first_piano.brand and first_piano.category and (first_piano.model or first_piano.size_cm > 0)
    show_serial_help: not first_piano or not first_piano.serial_number
    hide_serial_help: first_piano and first_piano.serial_number

conversation:
  - if: raw_user_input
    say: ${llm_response}
    actions: []

  - elif: no_brand
    say: >
      Let's start with the brand. What brand is your piano?
    actions: []

  - elif: no_category
    say: >
      What type of piano is it — upright or grand?
    actions: []

  - elif: no_model
    say: >
      Do you happen to know the model name or number?
    actions:
      - suggest_action: "I don’t know the model"
        trigger_event: set_model_dont_know

  - elif: no_size
    say: >
      Do you know the piano's size? (For upright: height. For grand: length)
    actions:
      - suggest_action: "I don’t know the size"
        trigger_event: set_size_dont_know

  - elif: no_serial
    say: >
      If you have the serial number, I can estimate the year.
    actions:
      - suggest_action: "Add serial number"
        route_to: "/pianos"
      - suggest_action: "I don’t know the serial number"
        trigger_event: set_serial_dont_know
      - suggest_action: "Where is the serial number?"
        trigger_event: show_serial_help
        if: show_serial_help

  - elif: can_save and not is_confirmed
    say: >
      You've entered enough information to register your piano. Please confirm if correct.
    actions:
      - suggest_action: "Confirm my piano"
        trigger_event: confirm_piano

  - elif: is_confirmed
    say: >
      ✅ Your piano has been successfully saved. Would you like to upload photos of it (optional)? Click ➕
    actions:
      - suggest_action: "Skip this step"
        trigger_event: skip_upload

  - elif: not user_profile.music_start_age
    say: >
      When did you start playing the piano, just out of curiosity?
    actions: []

  - elif: not user_profile.music_style or not user_profile.skill_level
    say: >
      What kind of music do you enjoy playing? And how would you describe your level?
    actions: []

  - else: true
    continue_if: first_piano.brand and first_piano.category and (first_piano.model or first_piano.size_cm)
    say: >
      Thank you so much for sharing all this with me, ${firstname}! You can now explore diagnosis, tutorials, or tuning options below.
    actions:
      - suggest_action: "Start diagnosis"
        route_to: "/diagnosis"
      - suggest_action: "Explore tuning options"
        route_to: "/tuner"

metadata:
  version: "3.0"
  lang: en
  allow_interruptions: true
  llm_backend: openai
  llm_model: gpt-3.5-turbo
  memory: true