name: welcome_agent
description: >
  PyTune AI Welcome Agent — guides users from profile to piano description, serial dating, and diagnostic journey.

triggers:
  - event: user_login
    condition: user_profile.logged_in and not user_profile.show_onboarding_dismissed

context:
  fetch:
    - user_profile
    - user_pianos
    - last_diagnosis
    - user_language
  variables:
    show_onboarding: >
      not user_profile.form_completed
      or user_pianos.count == 0
      or not last_diagnosis.exists

conversation:
  - if: "not user_profile.form_completed"
    say: >
      Hi ${firstname}, welcome to PyTune!
      Let's start with a few details about you to personalize your experience.
    actions:
      - suggest_action: "Complete my profile"
        route_to: "/profile"

  - elif: "user_pianos.count == 0"
    say: >
      I’d love to hear about your piano. Do you know the brand or serial number?
      We can try to date it and learn more together.
    actions:
      - suggest_action: "Describe my piano"
        route_to: "/pianos"

  - elif: "not last_diagnosis.exists"
    say: >
      Great! Now let’s check your piano’s acoustic condition with a short recording.
    actions:
      - suggest_action: "Run my first diagnosis"
        route_to: "/diagnosis"

  - else: true
    say: >
      Everything looks ready, ${firstname}! You can:
      - fine-tune your piano,
      - revisit your diagnosis,
      - or explore more info about your instrument.
    actions:
      - suggest_action: "Update my piano details"
        route_to: "/pianos"
      - suggest_action: "Check my last diagnosis"
        route_to: "/diagnosis/history"
      - suggest_action: "Start tuning"
        route_to: "/tuner"



prompt_template: |
  The user is on the dashboard and has completed their profile.
  They said: "$user_input"
  Context:
  - First name: $firstname
  - Has pianos: $user_pianos.count
  - Last diagnosis exists: $last_diagnosis.exists

  Respond as a helpful AI assistant. Encourage the user to either:
  - describe their piano (brand, serial),
  - date their piano,
  - start a diagnosis,
  - or explore tuning features.

metadata:
  version: "1.1"
  lang: en
  allow_interruptions: true